services:
  proxy:
    build:
      context: .
      dockerfile: traefik.Dockerfile
    container_name: Proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ssl/:/ssl/
    develop:
      watch:
        - action: rebuild
          path: traefik.yaml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  blackjack:
    container_name: Blackjack
    build:
      context: .
      target: development
    env_file: .env
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    labels:
      traefik.http.routers.tic-tac-toe-website.rule: Host(`localhost`)
      traefik.http.routers.tic-tac-toe-website.tls: true
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: Database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - blackjack_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  blackjack_postgres_data:
