apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-secret
  namespace: ${NAMESPACE}
stringData:
  DATABASE_HOST: "postgres-service.${POSTGRES_NAMESPACE}.svc.cluster.local"
  # TODO set secrets
