import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { Header } from "@/app/_components/Header";
import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/trpc/react";
import { type ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <TRPCReactProvider>
      <html lang="en" className={cn(GeistSans.variable, "min-h-screen")}>
        <body
          className={
            "grid-rows_[auto_1fr] bg-hero grid bg-cover bg-center bg-no-repeat"
          }
        >
          <Header />
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
