import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { Header } from "@/app/_components/Header";
import { TRPCReactProvider } from "@/trpc/react";
import { type ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <TRPCReactProvider>
      <html lang="en" className={GeistSans.variable}>
        <body className={"bg-hero bg-cover bg-center bg-no-repeat"}>
          <div className={"grid min-h-screen grid-rows-[auto_1fr]"}>
            <Header />
            {children}
          </div>
        </body>
      </html>
    </TRPCReactProvider>
  );
}
